### PR TITLE
v3: Reload configuration on SIGHUP

### PR DESCRIPTION
**Pull request by touhonoob**
to solve #19

### CODE REVIEW

**Comment by touhonoob** [comment]
rebased on master

**Comment by asn-d6** [comment]
Thanks for the work here. I'm also expecting unittests for this feature if possible.

**Comment by touhonoob** [comment]
@asn-d6 here's the test 
https://github.com/asn-d6/onionbalance/pull/31/files#diff-50e242fffca808cf94df8d7cd6309209
https://github.com/asn-d6/onionbalance/pull/31/files#diff-3d3dfc34e3a6ce80f105e8a97d4e5382

**Comment by asn-d6** [comment]
Hey Peter, this is great.

I see the functional test is breaking on CI.

Can you tell me how you ran the integration and unittests so that I can try to help you out here?

**Comment by touhonoob** [comment]
looking into it

**Comment by asn-d6** [comment]
> looking into it

eek failed again :/
What's the matter? Perhaps I can help u.

**Comment by touhonoob** [comment]
> > looking into it
> 
> eek failed again :/
> What's the matter? Perhaps I can help u.

chutney doesn't appear to be stable
Screenshot (21)

**Comment by asn-d6** [comment]
Will look into this @touhonoob . Thanks for your work.

**Comment by touhonoob** [comment]
Hi @ceresstation I think my work is done.

**Pull request merged**
